from __future__ import annotations

from typing import Any


def provider_directory_agent_cards() -> list[dict[str, Any]]:
    return [
        {
            "name": "source_retrieval_agent",
            "purpose": "Fetch public evidence snapshots from approved provider-directory sources.",
            "inputs": ["provider_id", "npi", "practice_id", "source_targets"],
            "outputs": ["raw_snapshot_uri", "retrieved_at", "source_terms_status", "source_cost_usd"],
            "tools": ["nppes_connector", "state_license_connector", "practice_website_fetcher", "cms_provider_data_connector"],
            "permissions": ["read_public_sources", "write_s3_raw_snapshot"],
            "forbidden_actions": ["write_directory_record", "delete_provider", "send_patient_data_to_model"],
            "handoff_to": ["evidence_normalization_agent"],
            "success_eval": "raw snapshot exists, source URL is retained, connector status is logged",
        },
        {
            "name": "evidence_normalization_agent",
            "purpose": "Normalize phone, address, specialty, license, NPI status, and patient-acceptance evidence.",
            "inputs": ["raw_snapshot_uri", "parser_version", "provider_context"],
            "outputs": ["normalized_evidence_rows", "parser_warnings", "llm_fallback_request"],
            "tools": ["deterministic_parser", "specialty_alias_table", "address_normalizer", "bedrock_fallback_contract"],
            "permissions": ["read_s3_raw_snapshot", "write_normalized_evidence"],
            "forbidden_actions": ["auto_apply_update", "ignore_unsupported_llm_span"],
            "handoff_to": ["identity_resolution_agent", "source_conflict_agent"],
            "success_eval": "all evidence rows carry field, value, source, URL, timestamp, and parser version",
        },
        {
            "name": "identity_resolution_agent",
            "purpose": "Resolve providers, practices, locations, affiliations, duplicates, and movement candidates.",
            "inputs": ["provider_record", "normalized_evidence_rows", "historical_directory_state"],
            "outputs": ["entity_match_decision", "duplicate_candidates", "movement_candidates", "practice_change_candidates"],
            "tools": ["npi_matcher", "address_matcher", "practice_change_detector", "duplicate_detector"],
            "permissions": ["read_directory_state", "write_identity_candidates"],
            "forbidden_actions": ["merge_identity_without_review", "infer_license_status_from_name_match"],
            "handoff_to": ["evidence_scoring_agent"],
            "success_eval": "identity-level changes are review-routed with evidence and confidence",
        },
        {
            "name": "source_conflict_agent",
            "purpose": "Adjudicate competing source values using field-specific source authority.",
            "inputs": ["normalized_evidence_rows", "field_authority_policy"],
            "outputs": ["source_conflict_rows", "authority_precedence_decision", "review_reason_code"],
            "tools": ["source_conflict_diagnostics", "field_authority_policy"],
            "permissions": ["read_normalized_evidence", "write_conflict_artifact"],
            "forbidden_actions": ["silently_drop_competing_values", "auto_apply_equal_authority_conflict"],
            "handoff_to": ["evidence_scoring_agent", "human_review_agent"],
            "success_eval": "all conflicting values show candidate source, competing source, and recommended action",
        },
        {
            "name": "evidence_scoring_agent",
            "purpose": "Score candidate updates for confidence, cost, freshness, source reliability, and auto-apply eligibility.",
            "inputs": ["normalized_evidence_rows", "identity_match_decision", "source_conflict_rows"],
            "outputs": ["candidate_updates", "auto_apply_updates", "review_queue"],
            "tools": ["confidence_scorer", "freshness_sla_checker", "cost_model", "review_priority_model"],
            "permissions": ["read_evidence_features", "write_candidate_updates"],
            "forbidden_actions": ["auto_apply_identity_level_change", "auto_apply_low_confidence_update"],
            "handoff_to": ["human_review_agent", "audit_rollback_agent"],
            "success_eval": "auto-apply precision remains at target and review queue carries reason codes",
        },
        {
            "name": "human_review_agent",
            "purpose": "Prepare reviewer worklists and capture accept, reject, edit, defer, recrawl, and rollback decisions.",
            "inputs": ["review_queue", "source_conflict_rows", "inactive_provider_candidates"],
            "outputs": ["review_disposition", "review_feedback_event", "learning_signal"],
            "tools": ["dashboard", "review_priority_queue", "case_study_generator"],
            "permissions": ["read_review_artifacts", "write_reviewer_disposition"],
            "forbidden_actions": ["hide_source_urls", "overwrite_audit_event"],
            "handoff_to": ["active_learning_agent", "audit_rollback_agent"],
            "success_eval": "reviewer can see source URLs, confidence, conflict reason, and rollback eligibility",
        },
        {
            "name": "audit_rollback_agent",
            "purpose": "Emit immutable audit events, provider timelines, and rollback commands for applied updates.",
            "inputs": ["candidate_updates", "review_disposition", "pipeline_version"],
            "outputs": ["audit_events_jsonl", "provider_change_timeline", "rollback_plan"],
            "tools": ["audit_event_writer", "rollback_plan_generator", "s3_archive_writer"],
            "permissions": ["write_audit_stream", "write_rollback_plan"],
            "forbidden_actions": ["mutate_prior_audit_event", "execute_rollback_without_approval"],
            "handoff_to": ["monitoring_agent"],
            "success_eval": "every applied update has an inverse rollback row and evidence hash",
        },
        {
            "name": "monitoring_agent",
            "purpose": "Watch connector freshness, false positives, review backlog, cost drift, and audit completeness.",
            "inputs": ["pipeline_metrics", "audit_events", "connector_status", "review_feedback"],
            "outputs": ["monitoring_alerts", "source_health_report", "cost_drift_report"],
            "tools": ["monitoring_alert_rules", "source_freshness_sla", "cost_per_1000_model"],
            "permissions": ["read_operational_metrics", "publish_alerts"],
            "forbidden_actions": ["change_thresholds_without_experiment", "page_without_owner"],
            "handoff_to": ["source_retrieval_agent", "human_review_agent"],
            "success_eval": "alerts identify owner, threshold, action, and rollback risk",
        },
    ]


def orchestrator_contract() -> dict[str, Any]:
    return {
        "name": "provider_directory_orchestrator",
        "style": "bounded multi-agent workflow",
        "state_store": "Aurora PostgreSQL for workflow state, S3 for immutable evidence/audit bundles",
        "message_bus": "Amazon SQS for review and connector work queues",
        "workflow": [
            "source_retrieval_agent",
            "evidence_normalization_agent",
            "identity_resolution_agent",
            "source_conflict_agent",
            "evidence_scoring_agent",
            "human_review_agent",
            "audit_rollback_agent",
            "monitoring_agent",
        ],
        "global_invariants": [
            "No gold labels or reviewer dispositions are available during candidate generation.",
            "No identity-level delete or inactive-provider update is auto-applied.",
            "Every source-derived value preserves source URL, retrieved timestamp, parser version, and evidence hash.",
            "Every applied update has an audit event and rollback command.",
            "LLM fallback outputs are review-routed unless corroborated by stronger deterministic sources.",
        ],
    }
